### ISSUE TITLE
Support to pass custom data/methods

### ISSUE THREAD

**Issue by gfviegas** [nicolasbeauvais/vue-social-sharing#13]
It would be nice to pass custom methods from my component to social sharing components. Let's say I have a custom click condition or something that needs to be trigged on the `network` tag.

I could do something like this:

```
<social-sharing url="example.com" :customMethods="myCustomMethods" inline-template>
   <network @click="customMethods.doSomethingCustom()">
   [....]
```

im a vue newbie so maybe that's not the best approach

**Comment by nicolasbeauvais** [comment]
I think a better way of doing this is to use the event fired by the library:

```javascript
this.$root.$on('social_shares_click', function (network, url) {
  // Do your thing here
});
```

**Comment by Dinuz** [comment]
Hello @nicolasbeauvais this doesn't really work for me.

I am trying to trigger a collapsable element outside the social-sharing component without luck.
I cannot leave the network element without a network= (otherwise the element just doesn't show up), and when I do define the network it just trigger the action of the network (in my case the email) I see the data-link property on it, but it doesn't trigger my custom method.

I do have something like this:
```
<template>
  <div>
    <social-sharing url="example.com" inline-template>
       <network @click="$parent.doSomethingCustom()"></network>
    </social-sharing>
    <collapse :open.sync="isOpen">
       <div>My Content to hide/show</div>
    </collapse>
  </div>
</template>

```

and inside of the methods I defined the doSomethingCustom() to toggle the collapsable component.

Could you please let me understand what should be done in order to trigger a collapsable component outside the social-sharing component, with a click on a network element of the social-sharing?

Thanks in advance

**Comment by Dinuz** [comment]
@nicolasbeauvais never mind, I did solve the issue:)
I just used the local call, and triggered it with that event.

BTW Thank you for the nice component
