### ISSUE TITLE
Components inside <network> do not render

### ISSUE THREAD

**Issue by lukeb** [nicolasbeauvais/vue-social-sharing#147]
I am attempting to use the FontAwesomeIcon component in a network element like this:

<template>
<SocialSharing inline-template>
      <div>
        <network network="facebook">
          <FontAwesomeIcon icon="fab facebook-f" />
          Facebook
        </network>
      </div>
    </SocialSharing>
</template>
<script>
import {FontAwesomeIcon} from '@fortawesome/vue-fontawesome';
import SocialSharing from 'vue-social-sharing';

export default {
  name: 'ShareButtons',
  components: {
    FontAwesomeIcon,
    SocialSharing
  }
};
</script>

Upon render, I get the following error: 
[Vue warn]: Unknown custom element: <FontAwesomeIcon> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by indr** [comment]
I just had a similar issue. The problem is that yo are using `social-sharing` with an [inline-template](https://vuejs.org/v2/guide/components-edge-cases.html#Inline-Templates) and therefore `social-sharing` has its own (child) scope and your FontAwesomeIcon component is registered on the (parent) `ShareButtons` component.

In my case, I want to access a computed property to configure the available networks. I use the [$parent](https://vuejs.org/v2/api/#vm-parent) instance property like described [on this StackOverflow question](https://stackoverflow.com/questions/45018831/vuejs-accessing-data-from-within-embedded-component-using-inline-template) to access it.

**Comment by nicolasbeauvais** [comment]
Thank you @indr for providing an explanation
