### ISSUE TITLE
URL is not reactive

### ISSUE THREAD

**Issue by iustin-ghe** [nicolasbeauvais/vue-social-sharing#153]
Hi,

First thing first: very nice plugin, thank you very much for sharing it!

Found the following issue: In my use case, the shared url contains an UUID that I fetch from an external service. If I bind the url property to a computed property, even though the computed does get updated, the rendered url is not.

I've created a fiddle to reflect it: https://codesandbox.io/embed/vue-template-dy3iy

Thank you!

**Comment by iustin-ghe** [comment]
According to the comments on this closed bug, this should be supported -> https://github.com/nicolasbeauvais/vue-social-sharing/issues/144

**Comment by nicolasbeauvais** [comment]
Hello @iustin-ghe,

if you click twice on the sharing link provided in your demo the URL is correctly set with the UUID, the issue here is that it is rendered before the call to the open method.

You could probably look for a workaround by pre-loading the data before the call to the open method to fix this issue.

I will look at the library core to see if I can move the rendering of the URL later in the execution process.

**Comment by MrToxy** [comment]
You have to keep in mind that state changes are async operations, so if you're changing ´fetchedId´ only when the user clicks the URL it doesn't mean that when it is opened the state has already been updated, and after the new window is created you can't assign anything new to it even if the props have been updated correctly, this would mean you have to recreate the window to reflect the changes.
