### ISSUE TITLE
null is not an object (evaluating 'r.focus')

### ISSUE THREAD

**Issue by blaaat** [nicolasbeauvais/vue-social-sharing#174]
I'm getting this error in my logs: 

> null is not an object (evaluating 'r.focus')

This is due content/popup blockers; can I suggest checking if popupWindow is non-null before calling popupWindow.focus (and other methods)

**Comment by nicolasbeauvais** [comment]
Hello @blaaat, could you share which  content/popup blocker do you use, so that I can replicate this error?

**Comment by hawkup** [comment]
I got this error too. Here are my environment and steps to reproduce.

### Environment
- Browser: Facebook in-app browser
- OS: ios 12.2
- device: iPhone SE


### Steps To Reproduce
1. Post https://nicolasbeauvais.github.io/vue-social-sharing/?path=/story/vuesocialsharing--dynamic-data to Facebook Timeline
2. Click open the posted link
3. Select the canvas tab
4. Click "Share on Twitter" button


### Screen record

![webview-window-open](https://user-images.githubusercontent.com/2748846/83346623-62df5e00-a348-11ea-9884-71c26120e5fb.gif)


### The current behavior

In-app browser throw null is not an object (evaluating 'r.focus') before redirecting.


### The expected behavior

Should not throw the error.

**Comment by nicolasbeauvais** [comment]
Thank you @hawkup for the detailed report, I'm on the go for the past few days and will try to take a look into this when I can!
