### ISSUE TITLE
Icons are not showing up as shown in demo

### ISSUE THREAD

**Issue by JosephWJMaxwell** [nicolasbeauvais/vue-social-sharing#253]
I am trying to get this to work on my project but the icons are not showing up as in the demo. I think it might have something to do with font awesome but I am not sure if you are using to pro version or not. This is my code for the vue-social-sharing `<ShareNetwork
      network="twitter"
      url="https://news.vuejs.org/issues/180"
      title="Say hi to Vite! A brand new, extremely fast development setup for Vue."
      description="This week, I’d like to introduce you to 'Vite', which means 'Fast'. It’s a brand new development setup created by Evan You."
      quote="The hot reload is so fast it\'s near instant. - Evan You"
      hashtags="vuejs,vite,javascript"
      twitterUser="youyuxi"
    >
    <i class="fab fah fa-lg fa-twitter"></i>
    <span>Share on Twitter</span>
  </ShareNetwork>`

this is the code importing the vue-social-sharing and font awesome in my main.js

```import { library } from '@fortawesome/fontawesome-svg-core'
import { faCoffee } from '@fortawesome/free-solid-svg-icons'
import { faJs, faVuejs } from '@fortawesome/free-brands-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import VueSocialSharing from 'vue-social-sharing'

Vue.use(VueSocialSharing);
library.add(faCoffee, faJs, faVuejs);

Vue.component('font-awesome-icon', FontAwesomeIcon)

Vue.config.productionTip = false
```
and this is how it looks on the website 
![image](https://user-images.githubusercontent.com/50028519/98048637-1cf95b00-1dfc-11eb-8969-d9474a3eca82.png)

**Comment by Kapcash** [comment]
**This is not related to the library.**
As the documentation mentions, the `ShareNetwork` component is _renderless_, so it doesn't ship with any default style.

----------------

That said, your problem is that you misuse the `vue/fontawesome` library. In order to to take advantage of webpack's tree-shaking, it doesn't export all the css files including all the icons classes (or your bundle size would increase considerably).

Instead, you have to use their exported custom component: `<font-awesome-icon icon="fa-lg fa-twitter" />`

Try this and hopefully you should see your icons :)
