### ISSUE TITLE
Can share from iOS and Android

### ISSUE THREAD

**Issue by SergioGMR** [nicolasbeauvais/vue-social-sharing#258]
The buttons doesn't work at iOS and Android, but at web them work.

![image](https://user-images.githubusercontent.com/2040454/101638221-b6ccad00-3a25-11eb-8163-cecff5b23bc4.png)
![image](https://user-images.githubusercontent.com/2040454/101638553-1d51cb00-3a26-11eb-8968-07a9b15d9374.png)

Thanks a lot

**Comment by aske-cph** [comment]
The buttons do not in Safari IOS on iPhone X for me either?

I don't have any content blockers installed but the "Content blocker" switch in Safari is on, which i reckon is default behaviour.

The plugin works fine in all Web browser and all other browsers on mobile, ie. Firefox, Chrome, Opera etc - it's only with Safari IOS that nothing happens. 

Since Safari IOS is quite i don't think this issue should be marked as stale. 

Also thanks for a great plugin!!

**Comment by nicolasbeauvais** [comment]
Hello, I do not have an Apple device, so I can't replicate the issue. 

Feel free to open a pull request if you find a fix for this.

**Comment by ezequiel88** [comment]
Ainda acontece comigo.
Iphone XS não funciona.
