### ISSUE TITLE
Lighthouse -  Links are not crawlable

### ISSUE THREAD

**Issue by shanks25** [nicolasbeauvais/vue-social-sharing#311]
Hi, I just added this plugin to my nuxt application , but after running lighthouse my SEO is showing 91 percent

![image](https://user-images.githubusercontent.com/40662526/164090520-8f06eef6-d65b-45db-8ff2-df19f7807bf2.png)

**Comment by Kapcash** [comment]
The reason is because the component renders links as anchors with an undefined javascript call as an `href` (i.e. `href="javascript:void(0)"`. That's an old technique that should not be used.

In my opinion, the component should render as `button`, not anchors that are not links. Maybe I'm missing a good reason the author decided to do this, but it feels wrong to me 😅
This will avoid many problems with SEO, and some edge cases like trying to open the link in a new tab that results in a blank page.

@nicolasbeauvais What do you think? Can we open a PR toward this solution?

**Comment by kissu** [comment]
Agreed with @Kapcash.

At the end, I'm not sure that this kind of popup should even be indexable, there is no real benefit for it IMO.
I'd code it and display a few links myself, or code something more clean (as suggested above).
Especially since nowadays people tend to prefer progressive enhancement and use less JavaScript overall, especially for things already supported by the browser.

**Comment by Kapcash** [comment]
Just pinging @nicolasbeauvais again so we can validate the solution to move from "javascript:void" to "button" and hopefully open a PR :)

**Comment by valere-hope** [comment]
From 100 to 83 seo score. Please move from "javascript:void" to "button" 

![Cattura](https://user-images.githubusercontent.com/112073672/227762081-3ecd78d0-4825-4cde-abac-a1f6ae701d4e.PNG)
